Repository GSG-G11/Tashteeb, pull requests merged in 2022-05, with the labels that each got.

#10 create header and navbar
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/Assets/01-Home-v1 1.svg
  client/src/Assets/Group 91.svg
  client/src/Assets/home-done.svg
  client/src/Component/Header/index.jsx
  client/src/Component/Header/style.css
  client/src/Component/Navbar/index.jsx
  client/src/Component/Navbar/style.css
  client/src/Component/Services/ServiceCard.jsx
  client/src/Component/Services/ServiceHolder.jsx
  client/src/Component/Services/style.css
  client/src/index.js
Labels: Done

#16 services component
  client/src/App.js
  client/src/Component/Home/index.jsx
Labels: Done

#17 made the product component
  client/package-lock.json
  client/package.json
  client/src/Component/products/productCard/index.jsx
  client/src/Component/products/productCard/style.css
Labels: Awaiting Review

#23 customize error
  server/src/app.ts
  server/src/error/customizeError.ts
  server/src/error/handleKnownError.ts
  server/src/error/handleUnkownError.ts
  server/src/error/index.ts
Labels: Awaiting Review

#20 Husky setup
  .commitlintrc.json
  .husky/commit-msg
  .husky/pre-commit
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Component/Header/index.jsx
  client/src/Component/Home/index.jsx
  client/src/Component/Navbar/index.jsx
  client/src/Component/NotFound/index.jsx
  client/src/Component/Services/ServiceCard.jsx
  client/src/Component/Services/ServiceHolder.jsx
  client/src/Pages/NotFound.jsx
  client/src/index.js
  package-lock.json
  package.json
Labels: Done, enhancement

#9 Engineer Component Front
  client/src/Component/EngineerCard/SingleCard/index.jsx
  client/src/Component/EngineerCard/index.jsx
  client/src/Component/EngineerCard/style.css
  client/src/Component/Home/index.jsx
Labels: Awaiting Review

#19 7 create footer
  client/package-lock.json
  client/package.json
  client/src/Component/EngineerCard/SingleCard/index.jsx
  client/src/Component/EngineerCard/index.jsx
  client/src/Component/Home/index.jsx
  client/src/Component/footer/Footer.jsx
  client/src/Component/footer/FooterHeader.jsx
  client/src/Component/footer/FooterTwitter.jsx
  client/src/Component/footer/FooterUl.jsx
  client/src/Component/footer/footer.css
  client/src/Component/products/productCard/index.jsx
  client/src/images/i1.jpg
  client/src/images/i2.jpg
  client/src/images/i3.jpg
  client/src/images/i4.jpg
  client/src/images/i5.jpg
  client/src/images/i6.jpg
  package-lock.json
  package.json
Labels: Awaiting Review

#24 created the service bar
  client/src/Component/servicesBar/index.jsx
  client/src/Component/servicesBar/style.css
Labels: Done

#25 21 handle signup
  client/src/Component/servicesBar/index.jsx
  jest.config.js
  package-lock.json
  package.json
  server/src/app.ts
  server/src/controller/userAuth/index.ts
  server/src/controller/userAuth/signup.ts
  server/src/database/FakeData/sync.ts
  server/src/database/config/connection.ts
  server/src/routes/index.ts
  server/src/test/products.test.js
  server/src/test/signupTest.test.ts
  server/src/validaiton/index.ts
  server/src/validaiton/signupValidation.ts
Labels: Done

#30 create signup modal
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Component/Modal/PasswordInput.jsx
  client/src/Component/Modal/Select.jsx
  client/src/Component/Modal/index.jsx
  client/src/Component/Modal/input.jsx
  client/src/Component/Modal/style.css
  client/src/Component/Navbar/index.jsx
Labels: Awaiting Review

#35 logout route and context
  client/src/App.jsx
  client/src/Component/AntdMessages.jsx/messages.jsx
  client/src/Component/Modal/PasswordInput.jsx
  client/src/Component/Modal/Select.jsx
  client/src/Component/Modal/index.jsx
  client/src/Component/Modal/input.jsx
  client/src/Component/Navbar/index.jsx
  client/src/Component/ProductDetailes/index.jsx
  client/src/Context/AuthContext.jsx
  client/src/index.jsx
  server/src/app.ts
  server/src/controller/userAuth/index.ts
  server/src/controller/userAuth/logout.ts
  server/src/routes/index.ts
  target/npmlist.json
Labels: Awaiting Review

#44 added login and auth/user and handled them in front end
  client/package-lock.json
  client/src/Component/Home/index.jsx
  client/src/Component/Modal/login.jsx
  client/src/Component/Navbar/index.jsx
  client/src/Component/servicesBar/style.css
  client/src/Context/AuthContext.jsx
  package-lock.json
  package.json
  server/src/app.ts
  server/src/auth/passport.ts
  server/src/controller/userAuth/index.ts
  server/src/controller/userAuth/login.ts
  server/src/controller/userAuth/signup.ts
  server/src/controller/userAuth/user.ts
  server/src/middlewares/admin.ts
  server/src/middlewares/engineer.ts
  server/src/middlewares/user.ts
  server/src/routes/index.ts
  server/src/validaiton/signinValidation.ts
Labels: Awaiting Review

#39 create user info section
  client/src/Assets/user.png
  client/src/Component/Modal/Select.jsx
  client/src/Component/Navbar/UserInfo.jsx
  client/src/Component/Navbar/index.jsx
  client/src/Component/Navbar/style.css
  package-lock.json
Labels: Awaiting Review

#40 get engineer [home page]
  client/src/Component/EngineerCard/SingleCard/index.jsx
  client/src/Component/EngineerCard/index.jsx
  client/src/Component/EngineerCard/style.css
  package.json
  server/src/app.ts
  server/src/controller/engineer/gitEngineer.ts
  server/src/controller/index.ts
  server/src/database/FakeData/fakeData.ts
  server/src/database/models/User.ts
  server/src/routes/index.ts
Labels: Done

#41 feat: create protected routes
  client/src/Component/Modal/index.jsx
  client/src/Component/Navbar/UserInfo.jsx
  client/src/Component/Navbar/index.jsx
  client/src/Context/AuthContext.jsx
  client/src/ProtectedRoutes/ProtectedRoutes.jsx
  server/src/controller/userAuth/signup.ts
  server/src/controller/userAuth/user.ts
  server/src/routes/index.ts
Labels: Done

#50 Engineers page
  client/src/App.jsx
  client/src/Component/Engineer/index.jsx
  client/src/Component/Engineer/style.css
  client/src/Component/EngineerCard/SingleCard/index.jsx
  client/src/Component/EngineerCard/index.jsx
  client/src/Component/EngineerCard/style.css
  client/src/Component/ProductDetailes/index.jsx
  client/src/Pages/EngineerPage.jsx
  server/src/app.ts
  server/src/controller/engineer/gitAllEngineers.ts
  server/src/controller/index.ts
  server/src/database/FakeData/fakeData.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#53 build: shopping summary
  client/src/Component/ShoppingSummary/index.jsx
  client/src/Component/ShoppingSummary/style.css
Labels: Awaiting Review

#48 get products endpoint
  client/package-lock.json
  client/src/Context/AuthContext.jsx
  package-lock.json
  server/src/auth/passport.ts
  server/src/controller/categories/getCategoriesController.ts
  server/src/controller/categories/index.ts
  server/src/controller/index.ts
  server/src/controller/products/getProductsController.ts
  server/src/controller/products/index.ts
  server/src/controller/routes/index.ts
  server/src/controller/userAuth/user.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#51 create dashboard page
  client/src/App.jsx
  client/src/Component/Dashboard/Orders.jsx
  client/src/Component/Dashboard/ProductList.jsx
  client/src/Component/Dashboard/Satistics.jsx
  client/src/Component/Dashboard/Table.jsx
  client/src/Component/Dashboard/index.jsx
  client/src/Component/Dashboard/style.css
  server/src/app.ts
  server/src/controller/index.ts
  server/src/controller/userAuth/signup.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#60 create github workflow for testing the routes
  .github/workflows/Test.yaml
  package-lock.json
  package.json
Labels: Done

#55 engineer profile [front && back]
  client/src/App.jsx
  client/src/Component/Engineer/index.jsx
  client/src/Component/EngineerCard/SingleCard/index.jsx
  client/src/Component/EngineerCard/index.jsx
  client/src/Component/ProductDetailes/index.jsx
  client/src/Component/ProductDetailes/style.css
  client/src/Component/Services/style.css
  client/src/Component/products/productCard/index.jsx
  client/src/Pages/EngineerPage.jsx
  client/src/Pages/EngineerProfile.jsx
  client/src/Pages/ProductProfile.jsx
  server/src/controller/engineer/gitEngineerById.ts
  server/src/controller/index.ts
  server/src/controller/products/gitProductById.ts
  server/src/controller/products/index.ts
  server/src/database/FakeData/fakeData.ts
  server/src/database/models/Product.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#64 code enhancment
  client/src/Component/products/productCard/index.jsx
  server/src/database/FakeData/fakeData.ts
  server/src/test/login.test.ts
Labels: Done

#57 create dashboard routes
  .github/workflows/Test.yaml
  client/src/App.jsx
  server/src/auth/passport.ts
  server/src/controller/index.ts
  server/src/controller/products/addProduct.ts
  server/src/controller/products/deleteProduct.ts
  server/src/controller/products/index.ts
  server/src/controller/products/updateProduct.ts
  server/src/controller/userAuth/user.ts
  server/src/database/FakeData/fakeData.ts
  server/src/middlewares/admin.ts
  server/src/middlewares/index.ts
  server/src/routes/index.ts
  server/src/test/login.test.ts
  server/src/test/productTests.test.ts
  server/src/validaiton/addProductValidation.ts
  server/src/validaiton/updateProductValidation.ts
Labels: Awaiting Review

#58 added cart route front & back
  client/package-lock.json
  client/src/App.jsx
  client/src/Component/CartRow/index.jsx
  client/src/Component/CartRow/style.css
  client/src/Component/Modal/login.jsx
  client/src/Component/NotFound/style.css
  client/src/Component/ShoppingSummary/index.jsx
  client/src/Component/ShoppingSummary/style.css
  client/src/Context/shoppingSummary.jsx
  client/src/Pages/Cart/Table.jsx
  client/src/Pages/Cart/index.jsx
  client/src/Pages/Cart/style.css
  package-lock.json
  server/src/app.ts
  server/src/controller/cart/checkout.ts
  server/src/controller/index.ts
  server/src/database/FakeData/sync.ts
  server/src/database/models/Category.ts
  server/src/database/models/HiringOrder.ts
  server/src/database/models/Order.ts
  server/src/database/models/Product.ts
  server/src/database/models/ProductOrder.ts
  server/src/database/models/Review.ts
  server/src/database/models/User.ts
  server/src/middlewares/index.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#62 test routes
  client/src/App.jsx
  client/src/Component/Engineer/index.jsx
  client/src/Component/EngineerCard/index.jsx
  client/src/Component/products/productCard/index.jsx
  client/src/Pages/EngineerProfile.jsx
  client/src/Pages/ProductProfile.jsx
  server/src/controller/engineer/gitAllEngineers.ts
  server/src/controller/engineer/gitEngineerById.ts
  server/src/controller/products/getProductById.ts
  server/src/controller/products/index.ts
  server/src/routes/index.ts
  server/src/test/engineers.test.ts
  server/src/test/productTests.test.ts
Labels: Awaiting Review

#67 Test Products And Categories
  client/src/App.jsx
  client/src/Pages/productsPage/index.jsx
  server/src/controller/index.ts
  server/src/routes/index.ts
  server/src/test/getCategoriesTest.test.ts
  server/src/test/getProductsTests.test.ts
Labels: Done

#74 Related products
  client/src/Component/RelatedProduct/index.jsx
  client/src/Component/RelatedProduct/style.css
  client/src/Pages/ProductProfile.jsx
  server/src/controller/index.ts
  server/src/controller/products/getProductsByCategory.ts
  server/src/controller/products/index.ts
  server/src/routes/index.ts
Labels: Done

#80 feat: Create Order Card
  client/src/Component/OrderCard/index.jsx
  client/src/Component/OrderCard/orderCard.css
Labels: Done

#81 create review router
  server/src/controller/Review/Review.ts
  server/src/controller/index.ts
  server/src/database/models/Review.ts
  server/src/routes/index.ts
  server/src/validaiton/review.ts
Labels: Done

#75 cloudinary functions
  client/package-lock.json
  package-lock.json
  package.json
  server/src/controller/cloudinaryController/index.ts
  server/src/controller/hiringOrder/index.ts
  server/src/controller/index.ts
  server/src/controller/products/addProduct.ts
  server/src/controller/products/getProductByCategory.ts
  server/src/controller/userAuth/signup.ts
  server/src/middlewares/cloudinary.ts
  server/src/middlewares/multer.ts
  server/src/routes/index.ts
  server/src/test/signupTest.test.ts
  server/src/validaiton/addProductValidation.ts
Labels: Done

#85 related product test
  server/src/controller/products/getProductByCategory.ts
  server/src/test/relatedProduct.test.ts
Labels: Awaiting Review

#83 cloudinary frontend
  client/package-lock.json
  client/package.json
  client/src/Component/Dashboard/AddProductModalContent.jsx
  client/src/Component/Dashboard/style.css
  client/src/Component/EngineerCard/SingleCard/index.jsx
  client/src/Component/Modal/index.jsx
  client/src/Component/Modal/style.css
  client/src/Component/ProductDetailes/index.jsx
  client/src/Component/products/productCard/index.jsx
  server/src/controller/products/addProduct.ts
  server/src/controller/userAuth/signup.ts
Labels: Done

#97 fix product cards not showing
  client/src/Pages/productsPage/index.jsx
  server/src/controller/products/getProductsController.ts
  server/src/controller/userAuth/signup.ts
Labels: Awaiting Review

#89 create protected routes
  client/src/App.jsx
  client/src/Component/Dashboard/index.jsx
  client/src/Component/Navbar/index.jsx
  client/src/Component/Navbar/style.css
  client/src/Pages/productsPage/index.jsx
  client/src/ProtectedRoutes/ProtectedRoutes.jsx
  package-lock.json
Labels: Awaiting Review

#94 handle hirng order card
  client/src/App.jsx
  client/src/Component/OrderCard/index.jsx
  client/src/Component/OrderCard/orderCard.css
  client/src/Pages/HiringOrder/index.jsx
  client/src/Pages/HiringOrder/style.css
  package-lock.json
  server/src/controller/Review/Review.ts
  server/src/controller/hiringOrder/completeService.ts
  server/src/controller/hiringOrder/getEngHirings.ts
  server/src/controller/hiringOrder/getUserHirings.ts
  server/src/controller/hiringOrder/index.ts
  server/src/controller/index.ts
  server/src/database/index.ts
  server/src/middlewares/regularUser.ts
  server/src/routes/index.ts
Labels: Done

#99 Fixed code [cloudinary, modle]
  client/src/App.css
  client/src/Component/Engineer/index.jsx
  client/src/Component/EngineerCard/SingleCard/index.jsx
  client/src/Component/Modal/Select.jsx
  client/src/Component/Modal/index.jsx
  client/src/Component/Navbar/index.jsx
  client/src/Component/ProductDetailes/index.jsx
  client/src/Component/RelatedProduct/index.jsx
  client/src/Component/RelatedProduct/style.css
  client/src/Component/products/productCard/index.jsx
  client/src/Pages/EngineerProfile.jsx
  client/src/Pages/ProductProfile.jsx
  server/src/controller/products/getProductsByCategory.ts
  server/src/controller/userAuth/signup.ts
  server/src/database/FakeData/fakeData.ts
  server/src/test/getProductsTests.test.ts
  server/src/test/relatedProduct.test.ts
  server/src/validaiton/signupValidation.ts
Labels: Awaiting Review

#100 fix: local storage doesnt work and image isnt being dispalyed
  client/src/Component/ShoppingSummary/index.jsx
  client/src/Component/products/productCard/index.jsx
  client/src/Pages/Cart/Table.jsx
Labels: Awaiting Review

#103 get orders back and front
  client/package-lock.json
  client/src/Component/Dashboard/OrderList.jsx
  client/src/Component/Dashboard/Orders.jsx
  client/src/Component/Dashboard/ProductList.jsx
  client/src/Component/Modal/dashProducts.jsx
  client/src/Component/OrderCard/index.jsx
  client/src/Context/ProductContext.jsx
  package-lock.json
  server/src/controller/hiringOrder/getAllOrders.ts
  server/src/controller/index.ts
  server/src/database/FakeData/fakeData.ts
  server/src/database/FakeData/sync.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#106 104 fit table pagination
  client/src/Component/Dashboard/ProductList.jsx
  client/src/Component/Dashboard/Table.jsx
  client/src/Context/ProductContext.jsx
  server/src/controller/products/getProductsController.ts
Labels: Awaiting Review

#109 Fixed code
  client/src/Component/Dashboard/ProductList.jsx
  server/src/controller/engineer/gitAllEngineers.ts
Labels: Awaiting Review

#117 add deploy on github actions
  .github/workflows/Deploy.yaml
Labels: Awaiting Review

#114 Fix footer and pagiantion
  client/src/Component/Home/index.jsx
  client/src/Component/footer/Footer.jsx
  client/src/Component/footer/footer.css
  client/src/Pages/productsPage/index.jsx
  client/src/Pages/productsPage/productsPage.css
Labels: Awaiting Review

#119 add start comand for building
  package.json
Labels: Awaiting Review

#108 fix: styling
  client/package-lock.json
  client/package.json
  client/src/Component/Badge/Badge.jsx
  client/src/Component/CartRow/index.jsx
  client/src/Component/EngineerCard/style.css
  client/src/Component/Navbar/UserInfo.jsx
  client/src/Component/Navbar/index.jsx
  client/src/Component/OrderCard/index.jsx
  client/src/Component/OrderCard/orderCard.css
  client/src/Component/products/productCard/index.jsx
  client/src/Component/products/productCard/style.css
  client/src/Context/AuthContext.jsx
  client/src/Pages/Cart/index.jsx
  client/src/Pages/HiringOrder/index.jsx
  client/src/Pages/HiringOrder/style.css
  package-lock.json
  server/src/controller/userAuth/login.ts
Labels: Awaiting Review

#121 Chart Dashboard
  client/package-lock.json
  client/package.json
  client/src/Component/Dashboard/Satistics.jsx
  client/src/Component/Dashboard/chart/CategoryChart/index.jsx
  client/src/Component/Dashboard/chart/OrderChart/index.jsx
  client/src/Component/Dashboard/chart/OrderChart/style.css
  client/src/Component/Dashboard/chart/Satistics/Card.jsx
  client/src/Component/Dashboard/chart/Satistics/Satistics.jsx
  client/src/Component/Dashboard/chart/Satistics/style.css
  client/src/Component/Dashboard/style.css
  server/src/controller/Satistics/index.ts
  server/src/controller/index.ts
  server/src/database/FakeData/fakeData.ts
  server/src/routes/index.ts
Labels: Awaiting Review

#124 add delpoy
  client/src/Component/Dashboard/AddProductModalContent.jsx
  client/src/Component/Dashboard/Modal.jsx
  client/src/Component/Dashboard/OrderList.jsx
  client/src/Component/Dashboard/ProductList.jsx
  client/src/Component/Dashboard/Table.jsx
  client/src/Component/Dashboard/UpdateModal.jsx
  client/src/Component/Dashboard/UpdateModalContent.jsx
  client/src/Component/Engineer/index.jsx
  client/src/Component/EngineerCard/index.jsx
  client/src/Component/OrderCard/index.jsx
  client/src/Component/ProductDetailes/index.jsx
  client/src/Component/RelatedProduct/index.jsx
  client/src/Component/ShoppingSummary/index.jsx
  client/src/Context/AuthContext.jsx
  client/src/Pages/EngineerProfile.jsx
  client/src/Pages/HiringOrder/index.jsx
  client/src/Pages/ProductProfile.jsx
  client/src/Pages/productsPage/index.jsx
  server/src/app.ts
  server/src/test/engineers.test.ts
  server/src/test/getCategoriesTest.test.ts
  server/src/test/getProductsTests.test.ts
  server/src/test/login.test.ts
  server/src/test/productTests.test.ts
  server/src/test/relatedProduct.test.ts
  server/src/test/signupTest.test.ts
Labels: Awaiting Review

#127 fix cart adding button
  client/package-lock.json
  client/package.json
  client/src/Component/products/productCard/index.jsx
  client/src/Context/AuthContext.jsx
Labels: Awaiting Review

#125 dashboard link and navbar position
  client/package-lock.json
  client/src/Component/Dashboard/chart/Satistics/Satistics.jsx
  client/src/Component/Dashboard/chart/Satistics/style.css
  client/src/Component/Dashboard/index.jsx
  client/src/Component/Dashboard/style.css
  client/src/Component/Navbar/index.jsx
  package-lock.json
Labels: Awaiting Review

#130 create about page
  client/src/App.jsx
  client/src/Component/AboutUs/about.jpg
  client/src/Component/AboutUs/index.jsx
  client/src/Component/AboutUs/style.css
  client/src/Component/Header/index.jsx
  client/src/Component/Header/style.css
Labels: Awaiting Review

#138 change total price data type
  client/package-lock.json
  client/src/Component/Dashboard/HiringOrders.jsx
  client/src/Component/Dashboard/HiringOrdersTable.jsx
  client/src/Component/Dashboard/chart/CategoryChart/index.jsx
  client/src/Component/Dashboard/chart/OrderChart/index.jsx
  client/src/Component/Dashboard/chart/Satistics/Satistics.jsx
  server/src/controller/cart/checkout.ts
  server/src/database/models/Order.ts
Labels: Awaiting Review

#140 fix: styling in general
  client/src/Component/Dashboard/style.css
  client/src/Component/Engineer/index.jsx
  client/src/Component/Engineer/style.css
  client/src/Component/EngineerCard/style.css
  client/src/Component/Navbar/style.css
  client/src/Component/ProductDetailes/index.jsx
  client/src/Component/ProductDetailes/style.css
  client/src/Component/footer/footer.css
  client/src/Component/servicesBar/index.jsx
  client/src/Component/servicesBar/style.css
  server/src/database/config/build.ts
Labels: Awaiting Review

#137 Fixed profile page
  client/package-lock.json
  client/src/Component/ProductDetailes/index.jsx
  client/src/Pages/EngineerProfile.jsx
  package-lock.json
  server/src/validaiton/signupValidation.ts
Labels: Awaiting Review

#144 feat: add favicon
  client/public/favicon.ico
  client/src/Component/Dashboard/style.css
  client/src/Component/Navbar/style.css
Labels: Awaiting Review

#131 feat: create readme file
  README.md
  client/public/index.html
  server/src/controller/Satistics/index.ts
Labels: draft
